### ISSUE TITLE
Creating project throws error when npm is used

### ISSUE THREAD

**Issue by Sun0fABeach** [phaser-cli/phaser-cli#13]
I get this error when I try to create a project:

    TypeError: env.isYarnOnline(...).then is not a function
    at run (/home/markus/.nvm/versions/node/v9.5.0/lib/node_modules/@phaser-cli/cli/phaserCli.js:75:6)
    at createProject (/home/markus/.nvm/versions/node/v9.5.0/lib/node_modules/@phaser-cli/cli/phaserCli.js:64:3)
    at Command.handleCreate [as handler] (/home/markus/.nvm/versions/node/v9.5.0/lib/node_modules/@phaser-cli/cli/phaserCli.js:25:3)
    at Cac.parse (/home/markus/.nvm/versions/node/v9.5.0/lib/node_modules/@phaser-cli/cli/node_modules/cac/dist/cac.js:418:27)
    at Object.<anonymous> (/home/markus/.nvm/versions/node/v9.5.0/lib/node_modules/@phaser-cli/cli/phaserCli.js:37:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

This disappeared after I installed yarn. The problem is that isYarnOnline returns a boolean instead of a promise when yarn is not installed, which is causing the type error.

**Comment by nerdenough** [comment]
Thanks for pointing that out, will release a patch to fix it soon.

**Comment by nerdenough** [comment]
Whoops, forgot merging a connected PR closes an issue. Have published a new version of Phaser CLI, would be cool if you could test it as well to confirm it's fixed for you. Will reopen this issue if it hasn't.

**Comment by Sun0fABeach** [comment]
Yep, fixed for me. Thanks!
