### ISSUE TITLE
CLI throws syntax error on Node v4

### ISSUE THREAD

**Issue by srobertson421** [phaser-cli/phaser-cli#4]
The following output appears when trying to use phaser-cli with Node v4:

```bash
$ phaser init webpack phaser-cli-test
/Users/username/.nvm/versions/node/v4.8.0/lib/node_modules/phaser-cli/bin/phaser-init:17
const { isLocalPath, getTemplatePath } = require('../lib/local-path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

Not looking for it to support older versions but maybe update the docs to say Node v6 is required rather than preferred.

**Comment by nerdenough** [comment]
Fixed - made the readme more explicit. Cheers.

**Comment by srobertson421** [comment]
Awesome! Thanks!
